"""partner field

Revision ID: 9fef8a7e9f41
Revises: 58a3b08536e6
Create Date: 2018-02-01 23:34:24.276560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fef8a7e9f41'
down_revision = '58a3b08536e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('partner', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'partner')
    # ### end Alembic commands ###
