"""partners stored by id

Revision ID: cec9dc73f976
Revises: dd11b15051b1
Create Date: 2018-02-06 18:27:04.509467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec9dc73f976'
down_revision = 'dd11b15051b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'p_id')
    # ### end Alembic commands ###
